create database BENGALURU;
USE  BENGALURU;
create TABLE METRO(
SL_NO INT auto_increment primary KEY,
LINE_NAME VARCHAR(50),
FROM_ VARCHAR(50),
TO_ VARCHAR(50),
DISTANCE_KM DECIMAL(5, 2),
TIMING DECIMAL(5, 2),
PRICE DECIMAL(5, 2),
TYPE_OF_TICKET VARCHAR(50),
NUMBER_OF_SATATION_IN_BETWEEN INT,
INTER_CHANGE_LINE_AT VARCHAR(50));

INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('PURPLE LINE','VJIYANAGAR','MEJESTIC',3.5,10.50,18,'coin',3,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('PURPLE LINE','MEJESTIC','VJIYANAGAR',3.5,10.50,18,'smart card',3,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('PURPLE LINE','MEJESTIC','K.R.KURAM',17.1,20,30,'QR CODE',3,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('GREEN LINE','SILK INSTIUTE','LABABAGH',3.5,10.50,18,'smart card',3,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('GREEN LINE','CHIKAPETE','LABABAGH',0.5,5,12,'COIN',1,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('GREEN LINE','MAJESTIC','RAJAJINAGAR',2.5,10.50,18,'smart card',3,'NO INTER CHANGE');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('GREEN LINE','SILK INSTIUTE','VIJANAGR',10.5,30.50,18,'QR CODE',17,'MAJESTIC');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('PURPLE LINE','MAGDI ROAD','PEENYA',6.8,18.30,35,'COIN',10,'MAJESTIC');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('PURPLE LINE',' M G ROAD','SIRAMPURA',7.5,25.50,25,'smart card',5,'MAJAESTIC');
INSERT INTO METRO(LINE_NAME ,FROM_ ,TO_ ,DISTANCE_KM ,TIMING ,PRICE ,TYPE_OF_TICKET ,NUMBER_OF_SATATION_IN_BETWEEN,INTER_CHANGE_LINE_AT) VALUES 
('GREEN LINE','SILK INSTIUTE','TRINTY',15.5,30.50,38,'Q R CODE',21,'MAJAESTIC');
select*from metro;
create table MOVIES(
     SL_NO INT auto_increment primary KEY,
     MOVIE_NMAE varchar(50),
     LANGUAGE_ VARCHAR(10), 
     GENERS varchar(10),  
     FORMAT_ varchar(10),
     DURATION_OF_MOVIE decimal(5,2),
     THETARE_NAME VARCHAR(20),
     NO_OF_SHOWS INT,
     THETARE_ADRESS varchar(50), 
     PRICE_OF_TICKET INT);
      insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('LEO','TELAGU','ACTION','2D',2.50,'VEERESH',3,'MAGADI ROAD',150);
        insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('GHOST','KANNADA','ACTION','2D',2.40,'VEERESH',3,'MAGADI ROAD',110);
        insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('Tagarupalya','KANNDA','COMEDY','2D',2.10,'GT MALLA',5,'MAGADI ROAD',250);
             insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('12TH FAIL','HINDI','DARAM','2D',2.27,'ORINA MALLA',3,'RAJKUMAR ROAD',350);
             insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('Bhagavanth Kesari','TELAGU','ACTION','2D',2.44,'GT MALLA',4,'MAGADI ROAD',10);
             insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('TRP RAMA','KANNDA','THIRLLER','2D',2.44,'LULU MALLA',4,'MAGADI ROAD',200);
             insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('Bhagavanth Kesari','KANNDA','ACTION','2D',2.44,'VEERESHA',4,'MAGADI ROAD',100);     
      insert INTO MOVIES (MOVIE_NMAE, LANGUAGE_ ,GENERS ,FORMAT_ , DURATION_OF_MOVIE ,THETARE_NAME , NO_OF_SHOWS ,THETARE_ADRESS ,PRICE_OF_TICKET)
      VALUES('Keedaa Cola','TELAGU','COMEDY','2D',2.44,'VEERESHA',4,'MAGADI ROAD',100);
      CREATE TABLE RESTAURANTS(
SL_NO int auto_increment primary KEY,
NAME_OF_RESTAURANT VARCHAR(45),
RATINGS FLOAT,
ADDRESS VARCHAR(25),
OPENS VARCHAR(25),
CLOSES VARCHAR(25),
CONTACT_NUMBER LONG,
TYPE_OF_RESTURANTS VARCHAR(25),
REVIEWS VARCHAR(25),
HOLIDAY VARCHAR(25)
);
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
VALUE('PALGUNI',7.5,'RING ROAD','6 AM','11 PM',9271615452,'VEG','GOOD','SUNDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('KRISHNA',8.1,'YASHVANTHPUR','5AM','12 PM',927192628,'N0N VEG','VERY GOOD','SUNDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('RAMA',9.0,'VIJAYA NAGAR','6 AM','11 PM',9271615452,'NON VEG','GOOD','MONDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('RAMESHWARA',7.9,'RAJAJI NAGAR','6 AM','10 PM',9271694452,'VEG','SUPER','SUNDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('PARVATHI',6.9,'NAGSANDRA','7 AM','11 PM',9741615452,'NON VEG','GOOD','TUESDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('RESTO BAR',6.9,'INDRA NAGAR','5 AM','12 PM',9296415452,'VEG','EXCELLENT','SUNDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('KALPATHARU',5.9,'SRIRAMPURA','9 AM','11 PM',927752452,'VEG','GOOD','SUNDAY');
INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('SHI KRISHNA',8.6,'MAIN ROAD','6 AM','10:30 PM',906543252,'NON VEG','GOOD','THURSDAY');
 INSERT INTO RESTAURANTS(NAME_OF_RESTAURANT,RATINGS ,ADDRESS ,OPENS ,CLOSES,CONTACT_NUMBER ,TYPE_OF_RESTURANTS,REVIEWS,HOLIDAY)
 VALUE('MAVITHA',6.0,'JAYA NAGAR','8 AM','11 PM',9279754352,'VEG','VERY GOOD','SUNDAY');
 select*FROM RESTAURANTS;
 CREATE TABLE MALLS(
NAME_OF_MALL VARCHAR(20),
PLACE VARCHAR(20),
NUMBER_OF_FLOORS INT,
NUMBER_OF_SHOPS INT,
EMPLOYEE INT,
MAINTENANCE_STAFF_NUM INT,
NUMBER_OF_AC INT,
NUMBER_OF_ESCALATOR INT,
OPEN_TIME VARCHAR(10),
CLOSE_TIME VARCHAR(10)
);
INSERT INTO MALLS VALUE('ORION MALL','BANGLORE',10,100,500,90,140,30,'9 AM','10 PM');
INSERT INTO MALLS VALUE('ELEMENT MALL','BANGLORE',6,150,550,100,160,50,'9 AM','10 PM');
INSERT INTO MALLS VALUE('LULU MALL','BANGLORE',8,120,510,70,180,30,'9 AM','10 PM');
INSERT INTO MALLS VALUE('FORUM MALL','BANGLORE',10,110,800,100,120,40,'9 AM','10 PM');
INSERT INTO MALLS VALUE('MANTRI SQUARE MALL','BANGLORE',9,115,600,90,160,25,'9 AM','10 PM');
INSERT INTO MALLS VALUE('GOPALAN MALL','BANGLORE',8,110,640,100,150,60,'9 AM','10 PM');
INSERT INTO MALLS VALUE('UB CITY','BANGLORE',10,160,250,120,130,45,'9 AM','10 PM');
INSERT INTO MALLS VALUE('GT WORLD MALL','BANGLORE',8,100,450,80,180,35,'9 AM','10 PM');
INSERT INTO MALLS VALUE('PARK SQUARE MALL','BANGLORE',13,110,580,110,150,68,'9 AM','10 PM');
INSERT INTO MALLS VALUE('1MG - LIDO MALL','BANGLORE',10,100,560,100,130,64,'9 AM','10 PM');
SELECT * FROM MALLS;
CREATE TABLE RESORT(
NAME_OF_RESORT VARCHAR(25),
PLACE VARCHAR(25),
RATING FLOAT,
NUMBER_OF_GAMES INT,
NUMBER_OF_ROOMS INT,
COST_TO_STAY INT,
COST_WITHOUT_STAY INT,
FOOD VARCHAR(25),
RESORT_OPENS_TIME VARCHAR(10),
RESORT_CLOSES_AT VARCHAR(20)
);
INSERT INTO RESORT VALUE('OCTAVE CASTLE SUITES','BANGLORE',4.3,20,30,2520,1500,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('GRAND MERCURE','BANGLORE',4.5,25,35,3000,1800,'VEG AND NON VEG','6AM','10PM');
INSERT INTO RESORT VALUE('HOTEL ROYAL ORCHID','BANGLORE',4.2,22,38,2440,1540,'VEG','7AM','10PM');
INSERT INTO RESORT VALUE('WINDFLOWER PRAKRUTHI','BANGLORE',4.4,28,45,2517,1080,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('ROYAL ORCHID','BANGLORE',4.3,29,33,2643,1800,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('ALOFT BENGALURU','BANGLORE',4.3,21,38,3500,2500,'NON VEG','7AM','10PM');
INSERT INTO RESORT VALUE('ZURI WHITEFIELD','BANGLORE',3.9,30,39,2956,1500,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('BLOOMROOMS','BANGLORE',3.4,35,44,3500,2710,'VEG AND NON VEG','6AM','10PM');
INSERT INTO RESORT VALUE('DAYS SUITES','BANGLORE',4.3,25,43,4000,2900,'VEG','6AM','10PM');
SELECT * FROM RESORT;
CREATE TABLE SHOWROOMS(
NAME VARCHAR(25),
PLACE VARCHAR(25),
RATNG INT,
OPEN_TIME VARCHAR(10),
CLOSE_TIME VARCHAR(10),
HOLIDAY VARCHAR(10),
TYPE_OF_SHOWROOM VARCHAR(20),
EMPLOYEES_NUM INT,
MAIN_BRANCH VARCHAR(20),
BUILDING_FLOORS INT
);
INSERT INTO SHOWROOMS VALUE('ADVAITH KIA','BANGLORE',4.3,'9AM','9PM','SUNDAY','CAR',40,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('MARUTHI SUZUKI','BANGLORE',4.4,'9AM','10PM','SUNDAY','CAR',60,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('NEXA','BANGLORE',4.2,'9AM','9PM','SUNDAY','CAR',30,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('SILICON HONDA','BANGLORE',4.3,'9AM','10PM','SUNDAY','CAR',50,'DELHI',2);
INSERT INTO SHOWROOMS VALUE('TANDAVA ARTS','BANGLORE',4.0,'9AM','9PM','SUNDAY','PLATES',45,'DELHI',5);
INSERT INTO SHOWROOMS VALUE('ROYAL ENFIELD','BANGLORE',3.9,'10AM','9PM','SUNDAY','BIKE',65,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('TATA SHOWROOM','BANGLORE',4.4,'9AM','9PM','SUNDAY','CAR',80,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('MG MOTOR INDIA','BANGLORE',4.2,'9AM','10PM','SUNDAY','CAR',55,'DELHI',2);
INSERT INTO SHOWROOMS VALUE('YAMAHA MOTOR','BANGLORE',4.1,'10AM','9PM','SUNDAY','BIKES',60,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('BATA SHOWROOM','BANGLORE',3.9,'9AM','9PM','SUNDAY','SHOE STORE',50,'DELHI',3);
SELECT * FROM SHOWROOMS;
ALTER table MALLS rename TO BENGALURU_MALLS;
ALTER table RESTAURANTS
ADD column ORIGIN_PLACE VARCHAR(50);
ALTER table SHOWROOMS
CHANGE COLUMN PLACE PALCE VARCHAR(10);
alter table RESTAURANTS
DROP column OPENS;
ALTER TABLE MOVIES
modify  column PRICE_OF_TICKET LONG;
DROP table BENGALURU_MALLS;
